### ISSUE TITLE
Can I use this lib with sdl?

### ISSUE THREAD

**Issue by Tavernari** [colyseus/colyseus-cocos2d-x#1]
I have a question about this, can I use this with pure c++?

**Comment by endel** [comment]
Hi @Tavernari, thanks for your interest! I'd really love to make this library generic for all C++ environments, but currently it is tied to cocos2d-x networking and callback system.

C++ targets I'd love to have also are:
- Unreal Engine
- Godot

I'm afraid each target would have its own peculiarities regarding threads or something, I'm not really a C++ developer, any advice you can give to allow this to happen would be very welcome!

**Comment by endel** [comment]
Closing as this should be tracked on https://github.com/colyseus/colyseus/issues/217
